### ISSUE TITLE
What does it do?  How do I use it?

### ISSUE THREAD

**Issue by MYeager1967** [angryelectron/xbmq-js#16]
The link to the documentation appears to be broken. I'm looking for a gateway that I can send and receive data from an XBee network via MQTT and this appears to be the solution. Any chance you could assist me in understanding how to use this?

**Comment by abythell** [comment]
All of the documentation for running xbmq is in the README, and I fixed one of the links to the [xbee-api](https://www.npmjs.com/package/xbee-api) package (The xbee-api message format is used to pass data through MQTT).  If there is another broken link, please specify what/where.

Here's another example that might help.  To start Node-Discovery on the XBee network, publish the following frame to the `rootTopic/gatewayIdentifier/request` topic:

```
 {
   "type": "0x08",
   "command": "ND"
}
```
xbmq will send an ND frame from the gateway XBee to the rest of the network.  When the remote nodes respond, the frames are converted back into xbee-api messages and published to `rootTopic/gatewayIdentifier/response`:

```
{
  "type":136,
  "command":"ND",
  "commandStatus":0,
  "nodeIdentification":{...}
}
```

**Comment by MYeager1967** [comment]
Ok, this appears to be my error as I was looking at several different sites at once and got mixed up. The broken link isn't on your page. I apologize for that. Do you have an example of an arduino client anywhere? I'm starting from scratch on this one and would really like to have an example to work from. Thanks for the response, it shows that the project isn't abandoned. I've found a few that have been in favor of cheaper radio gear...

**Comment by abythell** [comment]
It's important to point out that `xbmq` is a way of sending XBee API frames over MQTT, which is _not_ the same as sending MQTT over XBee.   I'm mentioning this because it is a common misconception.  

`xbmq` lets you do things like:

* bridge two geographically distinct XBee networks over a TCP network (Internet)
* publish XBee sensor data to non-XBee, but MQTT capable, sensors and clients
* send and receive XBee frames from web, smartphone, and desktop clients - no XBee required.

So,  if you have an Arduino connected to an XBee, you can send data from your Arduino to an MQTT broker using the [xbee-arduino](https://github.com/andrewrapp/xbee-arduino) library:

1.  Arduino generates and transmits XBee frame containing data
2. `xbmq` receives the XBee frame and converts it into an MQTT message (an xbee-api JSON string).
3. `xbmq` publishes the MQTT message to rootTopic/gatewayIdentifier/response topic on the broker
4. An MQTT client subscribed rootTopic/gatewayIdentifier/response receives the message, extracts the data from the xbee-api JSON string, and does something with the data.

**Comment by MYeager1967** [comment]
Looks like I'm on the wrong path...

What I'm doing now is sending and receiving  short messages in JSON format over XBEE from a Raspberry Pi to several Arduino devices. I'm processing all of this information and acting on or storing it myself. What I'm looking to do is use the Mosquitto server I'm already running to remove a few steps. Any suggestions where I might find what I'm looking for?

**Comment by abythell** [comment]
I would run `xbmq` on the RaspberryPi and send messages to/from the Arduinos using XBee API frames instead of custom JSON.  Done!  You could even wrap your JSON data into a TX frame if needed.

The xbee-arduino library makes it quite easy, and once you're in API mode you have access to so many more features of the XBee radio and network.  If you're just doing simple IO you can even ditch the Arduino and use the change-detect or periodic sampling features built-in to the XBee for simpler, cheaper, lower-power nodes.

Otherwise, if you're just using XBees in pasthrough/follower mode, I would replace your Arduino+XBee with cheap ESP8266 and just run MQTT clients on all your devices, assuming you have WiFi available to all nodes.

**Comment by MYeager1967** [comment]
I could probably go the WiFi route but I already have the XBee's. I also have a few places that I could likely get by with just an XBee attached to one of those relay boards. Haven't looked into how they work as of yet, but you know how that goes....
